require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable

  Exclude:
    - db/migrate/*
    - db/schema.rb
    - tmp/**/*
    - vendor/**/*

  TargetRubyVersion: 3.0

  DisplayCopNames: true

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*.rb'
