require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable

  Exclude:
    - db/migrate/*
    - db/schema.rb
    - tmp/**/*
    - vendor/**/*

  TargetRubyVersion: 3.2

  DisplayCopNames: true

Rails:
  Enabled: true

# We encourage `find_by_id!` (an alias for `find`), as it's more explicit that it's using raw IDs (not HashIDs).
Rails/DynamicFindBy:
  Whitelist: find_by_id! find_by_hashid find_by_hashid!

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*.rb'

Metrics/ClassLength:
  Max: 300
