name: RSpec

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rspec-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rspec-
    - name: Install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Create database
      run: |
        bundler exec rails db:setup RAILS_ENV=test
    - name: Run Rspec
      run: bin/rspec
