# Based on;
# https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
# https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html

name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      REDIS_URL: redis://localhost:6379


    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with: # uses version defined in `.ruby-version` file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Create database
      run: |
        bundler exec rails db:setup
    - name: Run Rspec
      run: bin/rspec
