name: TraceRoute

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-traceroute-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-traceroute-
    - name: Install traceroute gem
      run:
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run TraceRoute
      run: FAIL_ON_ERROR=1 bundle exec rake traceroute
